### ISSUE TITLE
Publish patch version with mocha as devDependency to resolve security vulnerability

### ISSUE THREAD

**Issue by G-Rath** [svg-sprite/svg-sprite#337]
I originally posted this as a [comment](https://github.com/jkphl/svg-sprite/pull/297#issuecomment-606396434) on the original PR, but am pulling it up into this issue for increased visibility and to make it easier to track.

Currently the latest version of `svg-sprite` has `mocha@5.2.0`  as a dependency, which pulls in a version of `mkdirp` that has a security vulnerability.

Since this is done via an extract constraint, there are three general ways for this to be resolved:

* Stop using `svg-sprite`
* `svg-sprite` publishes a new `1.5.x` version that doesn't have mocha as a dependency
* ~`mocha` publishes a new `5.2.x` version that uses the patched version of `mkdirp`.~

Since we like `svg-sprite`, we're left with options 2 & 3.

~For 3., I've opened an issue over at the [mocha](https://github.com/mochajs/mocha/issues/4220) repo asking if they would mind backporting it, but since that's not a sure thing I'm opening this issue here to cover solution 2.~

Mocha have since decided not to publish a backport to `5.2.x`, leaving us with just option 2.

`svg-sprite` is actually all ready to publish `v1.5.1`: Up until just after this [commit](https://github.com/jkphl/svg-sprite/commit/135cc82b3b2a71c1f03e81de179c45e69b71697e) everything was lined up, so it should just be a matter of checking that commit out and running `npm publish`.

Happy to help if possible!

**Comment by G-Rath** [comment]
Just an update: Mocha said that they were not going to backport an update of `mkdirp` to the `5.2.x` version given that it's over 2 years old.

This means we're left with option 2, which unfortunately doesn't look like it will happen anytime soon :/

**Comment by mhsalves** [comment]
They published an others minor versions like `0.5.3` and `0.5.5` and a major version `1.0.4`, using one of them is not an option ?

#### References
https://github.com/isaacs/node-mkdirp/releases/tag/v0.5.3
https://github.com/isaacs/node-mkdirp/releases/tag/v0.5.4
https://github.com/isaacs/node-mkdirp/releases/tag/v0.5.5
https://github.com/isaacs/node-mkdirp/releases/tag/v1.0.4

**Comment by mhsalves** [comment]
Other questiion, @jkphl how is the plan to publish a version `1.5.1` ?

**Comment by matthewjmink** [comment]
I'm unsure whether this should be tracked as a separate issue, but the `yargs` dependency also results in a Prototype Pollution vulnerability via `yargs-parser`. The `yargs` dependency also needs to be updated. https://www.npmjs.com/advisories/1500

**Comment by thomas-gordon** [comment]
I've made a small package that does the main thing we used svg-sprite for: turning a folder of svgs into a single sprite file. For now config is limited but it gets the job done without the excessive vulns/deps. I'm going to work on it over the next couple of months to power it up!

[svgsprite-file](https://www.npmjs.com/package/svgsprite-file)

**Comment by XhmikosR** [comment]
I've started working on getting v2.0.0 out. Ideally, we should have released a new patch version, but it's extra time I don't have at this point.

So, all of these issues will be fixed in v2.0.0. In the meantime, and assuming you don't mind installing the package from GitHub, you can use the master branch or temporarily https://www.npmjs.com/package/@twbs/svg-sprite/v/1.6.2 (https://github.com/svg-sprite/svg-sprite/compare/master...twbs:twbs) which we are using in https://github.com/twbs/icons.

**Comment by joaogarin** [comment]
Is there any change to release a patch version including the latest security updates merged in the master branch? This package https://github.com/svg-sprite/gulp-svg-sprite uses this package and for us it would be hard to really use another package at this point.

is the master branch here not the current 1.x version?

**Comment by XhmikosR** [comment]
Unfortunately, it's a total pain in the a$$ :/ I took a stab at at cutting a new version from v1.5.0, but people don't follow semver properly thus there are failures on Node.js 6.x.

The other thing I could try would be to build on top of v1.6.0 which we'll call it v2.0.0 due to the Node.js 6.x removal, which is what v1.6.0 should have been in the first place.

I'll try the second approach when I have some more time; in theory it should be easier than what I tried today from 1.5.x https://github.com/svg-sprite/svg-sprite/compare/v1.5.0...1.5.x

**Comment by XhmikosR** [comment]
Also, do note than there was a potential prototype pollution present in older versions; I'll try to pick that patch too if I manage to cut a new release.

**Comment by XhmikosR** [comment]
So, I spend some time and I managed to have a good branch, I believe: https://github.com/svg-sprite/svg-sprite/compare/v1.5.0...1.5.x

The downside is that due to svgo updating csso which in turn updated css-tree, Node.js 6.x support is gone. Now, I'm thinking, that even though technically this should have been a major version bump from our side, since it's not a direct error from our side I can just keep the package.json engines as it was and release it as a patch. That way all consumers of the package will get the update.

**Comment by XhmikosR** [comment]
I'm going to release the above as 1.5.1 tomorrow.

**Comment by XhmikosR** [comment]
1.5.1 is out https://github.com/svg-sprite/svg-sprite/releases/tag/v1.5.1
