### ISSUE TITLE
Upgrade to mocha v8.x to address vulnerability

### ISSUE THREAD

**Issue by tedw** [svg-sprite/svg-sprite#411]
Looks like the current version of `mocha` has a nested dep with a vulnerability:

Results of `$ npm audit` below:

| low      | Prototype Pollution |
| :----- | :----- |
| Package       | minimist |
| Patched in    | >=0.2.1 <1.0.0 || >=1.2.3 |
| Dependency of | svg-sprite |
| Path          | svg-sprite > mocha > mkdirp > minimist |
| More info     | https://www.npmjs.com/advisories/1179 |

Upgrading to v8 may require a little refactoring:
https://github.com/mochajs/mocha/releases/tag/v8.0.0

**Comment by XhmikosR** [comment]
This is already fixed in master. mocha shouldn't have been a dependency in the first place.

**Comment by tedw** [comment]
Ah ok, thanks for the quick reply! I was using the latest stable release (v1.5), will try switching to `v1.6.0-alpha`.

Just noticed all the updates you’ve made in the past week or so—thanks for doing that! Are you planning to publish a new release soon? Would be much appreciated 😄

**Comment by XhmikosR** [comment]
Yeah, I started backporting my changes with the plan to release v2.0. Technically v1.6.0 should have been v2.0.0 because it already drops Node.js 6 support.

You could try https://www.npmjs.com/package/%40twbs%2Fsvg-sprite (https://github.com/svg-sprite/svg-sprite/compare/master...twbs:twbs) in the meantime :)
